/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppData { 'tasks' : Array<Task>, 'projects' : Array<Project> }
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'none' : null } |
  { 'medium' : null };
export interface Project {
  'id' : ProjectId,
  'order' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export type ProjectId = string;
export type RecurringFrequency = { 'weekdays' : null } |
  { 'none' : null } |
  { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface Task {
  'id' : TaskId,
  'title' : string,
  'order' : bigint,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'priority' : Priority,
  'parentId' : [] | [TaskId],
  'recurringFrequency' : RecurringFrequency,
}
export type TaskId = string;
export type Timestamp = bigint;
export interface _SERVICE {
  'createProject' : ActorMethod<[string, string, bigint], Project>,
  'createTask' : ActorMethod<
    [
      ProjectId,
      [] | [TaskId],
      string,
      string,
      [] | [bigint],
      Priority,
      bigint,
      Array<string>,
      RecurringFrequency,
    ],
    Task
  >,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getData' : ActorMethod<[], AppData>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksByProject' : ActorMethod<[ProjectId], Array<Task>>,
  'saveAll' : ActorMethod<[Array<Project>, Array<Task>], undefined>,
  'updateProject' : ActorMethod<
    [ProjectId, string, string, bigint],
    [] | [Project]
  >,
  'updateTask' : ActorMethod<
    [
      TaskId,
      ProjectId,
      [] | [TaskId],
      string,
      string,
      [] | [bigint],
      Priority,
      boolean,
      bigint,
      Array<string>,
      RecurringFrequency,
    ],
    [] | [Task]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];