/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectId = IDL.Text;
export const Timestamp = IDL.Int;
export const Project = IDL.Record({
  'id' : ProjectId,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const TaskId = IDL.Text;
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'none' : IDL.Null,
  'medium' : IDL.Null,
});
export const RecurringFrequency = IDL.Variant({
  'weekdays' : IDL.Null,
  'none' : IDL.Null,
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'priority' : Priority,
  'parentId' : IDL.Opt(TaskId),
  'recurringFrequency' : RecurringFrequency,
});
export const AppData = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'projects' : IDL.Vec(Project),
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Project], []),
  'createTask' : IDL.Func(
      [
        ProjectId,
        IDL.Opt(TaskId),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
        Priority,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        RecurringFrequency,
      ],
      [Task],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getData' : IDL.Func([], [AppData], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByProject' : IDL.Func([ProjectId], [IDL.Vec(Task)], ['query']),
  'saveAll' : IDL.Func([IDL.Vec(Project), IDL.Vec(Task)], [], []),
  'updateProject' : IDL.Func(
      [ProjectId, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(Project)],
      [],
    ),
  'updateTask' : IDL.Func(
      [
        TaskId,
        ProjectId,
        IDL.Opt(TaskId),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
        Priority,
        IDL.Bool,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        RecurringFrequency,
      ],
      [IDL.Opt(Task)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectId = IDL.Text;
  const Timestamp = IDL.Int;
  const Project = IDL.Record({
    'id' : ProjectId,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const TaskId = IDL.Text;
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'none' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RecurringFrequency = IDL.Variant({
    'weekdays' : IDL.Null,
    'none' : IDL.Null,
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'projectId' : ProjectId,
    'priority' : Priority,
    'parentId' : IDL.Opt(TaskId),
    'recurringFrequency' : RecurringFrequency,
  });
  const AppData = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'projects' : IDL.Vec(Project),
  });
  
  return IDL.Service({
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Project], []),
    'createTask' : IDL.Func(
        [
          ProjectId,
          IDL.Opt(TaskId),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
          Priority,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          RecurringFrequency,
        ],
        [Task],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getData' : IDL.Func([], [AppData], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByProject' : IDL.Func([ProjectId], [IDL.Vec(Task)], ['query']),
    'saveAll' : IDL.Func([IDL.Vec(Project), IDL.Vec(Task)], [], []),
    'updateProject' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(Project)],
        [],
      ),
    'updateTask' : IDL.Func(
        [
          TaskId,
          ProjectId,
          IDL.Opt(TaskId),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
          Priority,
          IDL.Bool,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          RecurringFrequency,
        ],
        [IDL.Opt(Task)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };