/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type TaskId = string;
export interface Task {
    id: TaskId;
    title: string;
    order: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    updatedAt: Timestamp;
    projectId: ProjectId;
    priority: Priority;
    parentId?: TaskId;
    recurringFrequency: RecurringFrequency;
}
export type ProjectId = string;
export interface AppData {
    tasks: Array<Task>;
    projects: Array<Project>;
}
export interface Project {
    id: ProjectId;
    order: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
}
export enum Priority {
    low = "low",
    high = "high",
    none = "none",
    medium = "medium"
}
export enum RecurringFrequency {
    weekdays = "weekdays",
    none = "none",
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export interface backendInterface {
    createProject(name: string, description: string, order: bigint): Promise<Project>;
    createTask(projectId: ProjectId, parentId: TaskId | null, title: string, description: string, dueDate: bigint | null, priority: Priority, order: bigint, tags: Array<string>, recurringFrequency: RecurringFrequency): Promise<Task>;
    deleteProject(id: ProjectId): Promise<void>;
    deleteTask(id: TaskId): Promise<void>;
    getData(): Promise<AppData>;
    getProjects(): Promise<Array<Project>>;
    getTasks(): Promise<Array<Task>>;
    getTasksByProject(projectId: ProjectId): Promise<Array<Task>>;
    saveAll(incomingProjects: Array<Project>, incomingTasks: Array<Task>): Promise<void>;
    updateProject(id: ProjectId, name: string, description: string, order: bigint): Promise<Project | null>;
    updateTask(id: TaskId, projectId: ProjectId, parentId: TaskId | null, title: string, description: string, dueDate: bigint | null, priority: Priority, completed: boolean, order: bigint, tags: Array<string>, recurringFrequency: RecurringFrequency): Promise<Task | null>;
}
import type { AppData as _AppData, Priority as _Priority, Project as _Project, ProjectId as _ProjectId, RecurringFrequency as _RecurringFrequency, Task as _Task, TaskId as _TaskId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createProject(arg0: string, arg1: string, arg2: bigint): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2);
            return result;
        }
    }
    async createTask(arg0: ProjectId, arg1: TaskId | null, arg2: string, arg3: string, arg4: bigint | null, arg5: Priority, arg6: bigint, arg7: Array<string>, arg8: RecurringFrequency): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, to_candid_RecurringFrequency_n5(this._uploadFile, this._downloadFile, arg8));
                return from_candid_Task_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, to_candid_RecurringFrequency_n5(this._uploadFile, this._downloadFile, arg8));
            return from_candid_Task_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getData(): Promise<AppData> {
        if (this.processError) {
            try {
                const result = await this.actor.getData();
                return from_candid_AppData_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getData();
            return from_candid_AppData_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return result;
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByProject(arg0: ProjectId): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByProject(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByProject(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveAll(arg0: Array<Project>, arg1: Array<Task>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAll(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAll(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProject(arg0: ProjectId, arg1: string, arg2: string, arg3: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: TaskId, arg1: ProjectId, arg2: TaskId | null, arg3: string, arg4: string, arg5: bigint | null, arg6: Priority, arg7: boolean, arg8: bigint, arg9: Array<string>, arg10: RecurringFrequency): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, to_candid_RecurringFrequency_n5(this._uploadFile, this._downloadFile, arg10));
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, to_candid_RecurringFrequency_n5(this._uploadFile, this._downloadFile, arg10));
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppData_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppData): AppData {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringFrequency_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringFrequency): RecurringFrequency {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskId]): TaskId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_Task>;
    projects: Array<_Project>;
}): {
    tasks: Array<Task>;
    projects: Array<Project>;
} {
    return {
        tasks: from_candid_vec_n17(_uploadFile, _downloadFile, value.tasks),
        projects: value.projects
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    title: string;
    order: bigint;
    createdAt: _Timestamp;
    tags: Array<string>;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    updatedAt: _Timestamp;
    projectId: _ProjectId;
    priority: _Priority;
    parentId: [] | [_TaskId];
    recurringFrequency: _RecurringFrequency;
}): {
    id: TaskId;
    title: string;
    order: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    updatedAt: Timestamp;
    projectId: ProjectId;
    priority: Priority;
    parentId?: TaskId;
    recurringFrequency: RecurringFrequency;
} {
    return {
        id: value.id,
        title: value.title,
        order: value.order,
        createdAt: value.createdAt,
        tags: value.tags,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        updatedAt: value.updatedAt,
        projectId: value.projectId,
        priority: from_candid_Priority_n10(_uploadFile, _downloadFile, value.priority),
        parentId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.parentId)),
        recurringFrequency: from_candid_RecurringFrequency_n13(_uploadFile, _downloadFile, value.recurringFrequency)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "none" in value ? Priority.none : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weekdays: null;
} | {
    none: null;
} | {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): RecurringFrequency {
    return "weekdays" in value ? RecurringFrequency.weekdays : "none" in value ? RecurringFrequency.none : "monthly" in value ? RecurringFrequency.monthly : "daily" in value ? RecurringFrequency.daily : "weekly" in value ? RecurringFrequency.weekly : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Priority_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RecurringFrequency_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringFrequency): _RecurringFrequency {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskId | null): [] | [_TaskId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TaskId;
    title: string;
    order: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    updatedAt: Timestamp;
    projectId: ProjectId;
    priority: Priority;
    parentId?: TaskId;
    recurringFrequency: RecurringFrequency;
}): {
    id: _TaskId;
    title: string;
    order: bigint;
    createdAt: _Timestamp;
    tags: Array<string>;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    updatedAt: _Timestamp;
    projectId: _ProjectId;
    priority: _Priority;
    parentId: [] | [_TaskId];
    recurringFrequency: _RecurringFrequency;
} {
    return {
        id: value.id,
        title: value.title,
        order: value.order,
        createdAt: value.createdAt,
        tags: value.tags,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        updatedAt: value.updatedAt,
        projectId: value.projectId,
        priority: to_candid_Priority_n3(_uploadFile, _downloadFile, value.priority),
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        recurringFrequency: to_candid_RecurringFrequency_n5(_uploadFile, _downloadFile, value.recurringFrequency)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.none ? {
        none: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringFrequency): {
    weekdays: null;
} | {
    none: null;
} | {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == RecurringFrequency.weekdays ? {
        weekdays: null
    } : value == RecurringFrequency.none ? {
        none: null
    } : value == RecurringFrequency.monthly ? {
        monthly: null
    } : value == RecurringFrequency.daily ? {
        daily: null
    } : value == RecurringFrequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Task>): Array<_Task> {
    return value.map((x)=>to_candid_Task_n19(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
